# Generated by Django 2.1.4 on 2018-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pickup_point', models.CharField(max_length=255)),
                ('flight_time', models.CharField(max_length=255)),
                ('airline', models.CharField(max_length=255)),
                ('aircraft_type', models.CharField(max_length=255)),
                ('tail_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
