# Generated by Django 2.1.4 on 2019-01-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='date',
            new_name='flight_date',
        ),
    ]
