# Generated by Django 2.1.4 on 2019-01-09 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190109_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
