# Generated by Django 2.1.4 on 2019-01-09 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20190109_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flights',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_date',
            field=models.CharField(max_length=255),
        ),
    ]
