# Generated by Django 2.1.4 on 2019-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20190305_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
